### PR TITLE
Fix for windows users

### LINKED ISSUE #9: The setup doesn't appear to be working from a windows environment
Comment from Hacker News: https://news.ycombinator.com/item?id=9799539

Full description: 
>The setup doesn't appear to be working from a windows/mingw32 environment. (Most npm installers do work in this environment.)

### PR DESCRIPTION
**Pull request by Semigradsky**
Fix #9

### CODE REVIEW

**Comment by eTorAken** [comment]
I think `ncp` has to be installed globally with `npm install ncp -g` to work as you intend (I don't think installing it in local directory is enough). Thus, it should be added to the doc.

**Comment by Semigradsky** [comment]
The global installation isn't needed

https://docs.npmjs.com/cli/run-script

> In addition to the shell's pre-existing PATH, npm run adds node_modules/.bin to the PATH provided to scripts. Any binaries provided by locally-installed dependencies can be used without the node_modules/.bin prefix. For example, if there is a devDependency on tap in your package, you should write "scripts": {"test": "tap test/\*.js"} instead of "scripts": {"test": "node_modules/.bin/tap test/\*.js"} to run your tests.

**Comment by voter101** [comment]
Hello!

I am working on it. Your script works, but there are some more stuff, we need to fix there (and I'm on it):

1. One of NPM packages requires python - Windows users needs to install it, to make it working
2. `test-es6` command does not work, I am rewriting it to node script.

**Comment by Semigradsky** [comment]
`npm run test-es6` in this PR works for me (Windows 8)

**Comment by voter101** [comment]
What's your setup? I installed mingw with some basic packages (and python of course). It does not work for me because of path problems and `true` keyword not being recognized.

**Comment by eTorAken** [comment]
Okay @Semigradsky, thanks for the tip!

**Comment by voter101** [comment]
Thanks for that fix @Semigradsky - I will merge it and add information about python.

About my problems with shell - it was my misconfigured mingw. Sorry for that.

**Comment by eTorAken** [comment]
@voter101 how did you fix it? I got this error trying to run it:
```sh
$ npm run test-es6

> reactjs_koans@0.0.1 test-es6 c:\wamp\www\reactjs_koans
> jsx -x jsx --es6module exercises/es6 src/es6 >/dev/null && mocha -b --compilers js:mocha-traceur -r test/es6/helpers.js test/es6/**/*.js & true

The specified path was not found.
```

Can open an issue if necessary.

**Comment by voter101** [comment]
Hey @eTorAken 

I'll reopen the issue #9 and make it working on bare node + python installation. Thanks for reporting.

**Pull request merged**
