### PR TITLE
Less verbose syntax for binding, plus explainer

### PR DESCRIPTION
**Pull request by carver**
I left out the bit about arrow functions in the comment, it seemed like there was enough going on.  It made sense to wait to explain this, so that you know about binding and why it's important before you see a less explicit method for binding.

@see http://babeljs.io/blog/2015/06/07/react-on-es6-plus/

### CODE REVIEW

**Comment by voter101** [comment]
Wow. That makes the fragments on autobinding easier to understand. Thanks!

I guess we need to rework some fragment of koans (including quiz :) )

**Comment by voter101** [comment]
The only thing that bothers me is usage of Property Initializers, which are used in ES7 (we wanted to stick  to ES6). I'll leave some time for more people to discuss that matter here.

**Comment by carver** [comment]
I knew this was pre-release syntax, but didn't understand just how early it was until reading this:
https://babeljs.io/docs/usage/experimental/

This is clearly a long way from being standard (they call it "Strawman" proposal, there).  I wish the blog post had been clearer on that point.

I agree this syntax is not ready.  Closing...

**Comment by voter101** [comment]
We just need to wait for that. Patiently... :)

**Pull request closed without merging**
